version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: timely-postgres
    environment:
      POSTGRES_DB: timely
      POSTGRES_USER: timely_user
      POSTGRES_PASSWORD: timely_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timely_user -d timely"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: